insert

account sub entity
	has duration
	has current_balance
	has installment_rate
	has cc_age

	has purpose
	has over_draft
	has credit_history
	has Average_Credit_Balance
	has other_parties
	has other_payment_plans
	has is_fraudulent
	plays asset;

person sub entity
	has personal_status
	has num_dependents
	has is_foreign_worker
	has existing_credits
	plays worker
	plays holder
	plays resident;

job sub entity
	has name #{ 'unemp/unskilled non res', 'unskilled resident', skilled, 'high qualif/self emp/mgmt'}
	plays employment;

property sub entity #{ 'real estate', 'life insurance', car, 'no known property', telephone} Cominbing two fields in the original data
	has name
	plays asset;

residence sub entity 
	has ownership_type #{rent, own, for free}
	plays home;

phone sub entity
	plays asset;
	



