account sub entity
	has credit_usage
	has age
	has credit_usage
	has current_balance
	has installment_rate
	has residence_since
	has cc_age
	has existing_credits
	has num_dependents

	has over_draft
	has credit_history
	has purpose
	has Average_Credit_Balance
	has employment
	has other_parties
	has other_payment_plans
	plays asset

person sub entity
	has housing
	has job
	has employment_length
	has num_dependents
	plays holder
	plays resident

property sub entity #{ 'real estate', 'life insurance', car, 'no known property', telephone} Cominbing two fields in the original data
	has name
	plays asset

residence sub entity #{rent, own, for free}
	has ownership_type 
	has resident_since #not the best design - better to have this as a resource on the relationship. However, this would lead to an extra relationship chain in Amie+.
	plays home


foreign_worker sub person
national_worker sub person
	



