insert

holder sub role;
asset sub role;
home sub role;
resident sub role;
worker sub role;
employment sub role;

#qualitative types written as roles

holds sub relation
	relates holder
	relates asset;

livesIn sub relation
	relates resident
	relates home;

worksAs sub relation
	relates worker
	relates employment;
